### ISSUE TITLE
Prior Inclusion Probabilities Issue

### ISSUE THREAD

**Issue by Chyvan** [steve-the-bayesian/BOOM#15]
Currently working with the BSTS package.

I have 120 predictors and define the expected model size as 5. As the prior inclusion probability is defined as expected model size/predictors, the prior inclusion probability should be 0.416. But when check it in the stored bsts model, I can see that it is 0.413. This equals to 5/121. Why is that?

**Comment by steve-the-bayesian** [comment]
Most likely because an intercept is being added.  You can get rid of it by
adding a "-1" to your model formula, as in " y ~ . - 1".

**Comment by Chyvan** [comment]
ok, thank you for the fast reply!

I have some further questions concerning the package bsts and the method explained in the paper Predicting the Present with BSTS(2014) and Bayesian Variable Selection for Nowcasting Economic
Time Series(2015). Is there some other possibility to contact you?

**Comment by steve-the-bayesian** [comment]
steve.the.bayesian@gmail.com
