### ISSUE TITLE
R crashing with Google xts/zoo examples

### ISSUE THREAD

**Issue by furchtgott** [steve-the-bayesian/BOOM#36]
R crashes with the "fatal error" message when I try the Google example. I have tried this in R 3.5.1 and 3.6.0. I also tried converting goog to zoo but I am getting the same behavior.

data(goog)
ss <- AddSemilocalLinearTrend(list(), goog)
model <- bsts(goog, state.specification = ss, niter = 500)

**Comment by steve-the-bayesian** [comment]
Thanks for the bug report.  I'll investigate.

**Comment by steve-the-bayesian** [comment]
This code works:
set.seed(8675309)
library(bsts)
data(goog)
goog <- as.numeric(goog)             ## LOOK HERE
ss <- AddSemilocalLinearTrend(list(), goog)
model <- bsts(goog, ss, niter = 50)

This code crashes:
set.seed(8675309)
library(bsts)
data(goog)
goog <- zoo(as.numeric(goog), index(goog)) .  #### LOOK HERE
ss <- AddSemilocalLinearTrend(list(), goog)
Model <- bsts(goog, ss, niter = 50)

This indicates that the problem has something to do with handling timestamps in zoo objects.  XTS is a generalization of zoo, so fixing one likely fixes the other.

**Comment by steve-the-bayesian** [comment]
Found the bug.  An offset translating from R to C indexing was being subtracted twice.

**Comment by steve-the-bayesian** [comment]
I'll get this fix live on CRAN ASAP.  It might take a week to get through their processes.   In the mean time if anyone needs the updated source just send an email.

**Comment by steve-the-bayesian** [comment]
bsts bug fix accepted to CRAN on 6/7/2019
