### ISSUE TITLE
Boom package takes over 600 mb after installing with R

### ISSUE THREAD

**Issue by santhisenan** [steve-the-bayesian/BOOM#58]
I am trying to install BSTS R package on a docker container. Boom package is installed in ```usr/local/lib/R/site-library/Boom```. However, the size of the file `libboom.a` is over **600 mb**.

Is there a way to reduce the file size for this file as I am trying to make my container leaner.

![image](https://user-images.githubusercontent.com/14852343/128482511-2e00b5af-ac27-42a0-9865-85e4bc0f2607.png)

To reproduce this, build using this Dockerfile:

```docker
FROM rocker/r-base:4.1.0 AS compile-image
RUN apt-get update \
    && mkdir $HOME/.R
COPY Makevars .R/

RUN wget "https://cran.r-project.org/src/contrib/Boom_0.9.7.tar.gz"
RUN R CMD INSTALL --strip --clean "Boom_0.9.7.tar.gz"
```

I added the `--strip` argument as it is suggested in [this blog post](http://dirk.eddelbuettel.com/blog/2019/03/27/).

This is the Makevars file:
```make
SHLIB_CXXLDFLAGS = -Wl,-S -shared
SHLIB_CXX11LDFLAGS = -Wl,-S -shared
SHLIB_CXX14LDFLAGS = -Wl,-S -shared
SHLIB_FCLDFLAGS = -Wl,-S -shared
SHLIB_LDFLAGS = -Wl,-S -shared

# strip debug symbols for smaller Linux binaries
strippedLib: $(SHLIB)
    if test -e "/usr/bin/strip" & test -e "/bin/uname" & [[ `uname` == "Linux" ]] ; \
        then /usr/bin/strip --strip-debug $(SHLIB); fi
.phony: strippedLib
```

**Comment by steve-the-bayesian** [comment]
If you manually strip the library using the bash "strip" utility it will be
significantly smaller.

**Comment by santhisenan** [comment]
Thank you Steve for your reply.

I ran `strip --strip-unneeded usr/local/lib/R/site-library/Boom/lib/libboom.a` after installing the library. The file size reduced to just **30mb**. Hope it does not affect the BSTS package.

![image](https://user-images.githubusercontent.com/14852343/128583654-d9eddbe1-1b61-4750-bd2d-1b0b62300618.png)
